server:
  port: 8080

spring:
  application:
    name: CustomerAI
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/customerai
    username: customerai
    password: customerai
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  ai:
    ollama:
      embedding:
        model: mxbai-embed-large
      chat:
        options:
          model: llama3
          temperature: 0.5
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1024
        initialize-schema: true
#  ai:
#    vectorstore:
#      pgvector:
#        schema-validation: true

application:
  webClientConfig:
    timeout: 10000
    backoffRetry: 5
    backoffPeriod: 10000

weather:
  api-key: ${WEATHER_API_KEY}
  api-url: https://api.weatherapi.com/v1